repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [
          --config=.flake8,
        ]
        additional_dependencies:
          - flake8-builtins==1.5.3
          - flake8-commas==2.0.0
          - flake8-debugger==4.0.0
          - flake8-comprehensions==3.3.1
          - flake8-eradicate==1.0.0
          - dlint==0.11.0

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Isort
        args: [
          --sp=.isort.cfg,
        ]
        exclude: ^.*/?setup\.py$
        additional_dependencies: [toml]
